name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
      
    - name: reconfig autotools for different version
      run: autoreconf
    
    - name: configure
      run: ./configure
      
    - name: build
      run: make
      
    - name: run executable
      run: src/ransfoil --script ransfoil.configxyz
      
    - name: clean
      run: make distclean
